# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb70d7b75719099645739ec5357215b620a3b21ce24280d29f326a47c7979095acf547cae14b4c7c8d6c185197001b7a5ae4fc93be8442ad5bb36e5c5050a85c

test:
  secret_key_base: c0fe5aad2b12e3cb3913ea235c6f55b1d006f39d447136d0ec5cce349c01fd865c86ae24aca8817a88f59b66f458f393c0e99baccdf7004d0ce466e48626e663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
